<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>52436cea-d12e-4772-978f-1dc2591a470e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.8" />
  </ItemGroup>

</Project>
